name: Build and Deploy FastAPI App to Azure Web App

on:
  push:
    branches:
      - main  # Trigger on the main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
            
      
      - name: 'Set up Python'
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

     
      
      - name: 'Set up Docker Buildx'
        uses: docker/setup-buildx-action@v2

      - name: 'Login to Azure'
        uses: azure/login@v1
        with:
          #creds: '{"clientId":"d628f8fa-ac3e-4a7a-a7e8-bc386cb884d4","clientSecret":${{ secrets.AZURE_CREDENTIALS }},"subscriptionId":"5cb9d786-4789-4403-9c63-44493daf4bbd","tenantId":"8d7d67b6-2968-4815-9c54-4906afe68b5c"}'
          creds: '{"clientId":"d628f8fa-ac3e-4a7a-a7e8-bc386cb884d4","clientSecret":"AJf8Q~P0vKPxFBv6FqBjT6dLwojUnAkcjLNasbwg","subscriptionId":"5cb9d786-4789-4403-9c63-44493daf4bbd","tenantId":"8d7d67b6-2968-4815-9c54-4906afe68b5c"}'
          #creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: 'Set up Docker Compose'
        uses: docker/setup-buildx-action@v2

      - name: 'Login to Azure Container Registry'
        run: |
          echo "GhcOYAY8Upxcv2m1YJMOki8vaA7WdF01Sgh+EWj1hY+ACRDDub0R" | docker login yorkvilleregistry.azurecr.io -u yorkvilleregistry --password-stdin


      - name: 'Define IMAGE_TAG'
        run: echo "IMAGE_TAG=smalltest-fastapi:$(date +%Y%m%d%H%M%S)" >> $GITHUB_ENV

      - name: 'Build and push Docker image'
        run: |
          
          docker buildx build --platform linux/amd64 --no-cache -t yorkvilleregistry.azurecr.io/${{ env.IMAGE_TAG }} -f Dockerfile_fastapi . --load
          docker push yorkvilleregistry.azurecr.io/${{ env.IMAGE_TAG }}

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'YorkvilleCharlie'
          images: 'yorkvilleregistry.azurecr.io/${{ env.IMAGE_TAG }}'
