
name: Build and Deploy FastAPI App to Azure Web App

on:
  push:
    branches:
      - incr2  # Trigger on the incr2 branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v2

      - name: 'Login to Azure'
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: 'Set up Python'
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: 'Install dependencies'
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: 'Configure Azure App Service Settings'
        uses: azure/appservice-settings@v1
        with:
          app-name: 'YorkvilleCharlie'
          app-settings-json: |
            [
              {
                "name": "OPENAI_API_KEY",
                "value": "${{ secrets.OPENAI_API_KEY }}",
                "slotSetting": false
              },
              {
                "name": "AZURE_STORAGE_ACCOUNT_KEY",
                "value": "${{ secrets.AZURE_STORAGE_ACCOUNT_KEY }}",
                "slotSetting": false
              }
            ]
          startup-command: 'python main.py'


          
      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'YorkvilleCharlie'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: .




